"""Add visitor code to visits

Revision ID: 0747d7e324dc
Revises: 6f03dd1b586b
Create Date: 2026-08-21 13:48:57.680946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0747d7e324dc'
down_revision = '6f03dd1b586b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('visitor_code_generated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_visits_visitor_code'), ['visitor_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_visitor_code'))
        batch_op.drop_column('visitor_code_generated_at')
        batch_op.drop_column('visitor_code')

    # ### end Alembic commands ###
