"""Add visitor access pass fields

Revision ID: 1072d78ae2cd
Revises: cc6309c9ce6c
Create Date: 2026-08-26 10:27:05.687264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1072d78ae2cd'
down_revision = 'cc6309c9ce6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_pass_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('access_pass_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('official_invitation_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_visits_access_pass_token'), ['access_pass_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_access_pass_token'))
        batch_op.drop_column('official_invitation_sent_at')
        batch_op.drop_column('access_pass_generated_at')
        batch_op.drop_column('access_pass_token')

    # ### end Alembic commands ###
