"""add visit invitations and notifications

Revision ID: 636fe3782827
Revises: 953963968848
Create Date: 2026-08-19 22:24:50.304400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '636fe3782827'
down_revision = '953963968848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_audits',
    sa.Column('visit_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_audits_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_audits_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_audits_visit_id'), ['visit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_audits_visit_id'))
        batch_op.drop_index(batch_op.f('ix_visit_audits_user_id'))
        batch_op.drop_index(batch_op.f('ix_visit_audits_action'))

    op.drop_table('visit_audits')
    # ### end Alembic commands ###
