"""add visit invitations and notifications

Revision ID: 793b314ca744
Revises: 636fe3782827
Create Date: 2026-08-19 22:57:22.851143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '793b314ca744'
down_revision = '636fe3782827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_invitations',
    sa.Column('visit_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_invitations_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_visit_invitations_visit_id'), ['visit_id'], unique=False)

    op.create_table('visit_notifications',
    sa.Column('visit_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_notifications_visit_id'), ['visit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_notifications_visit_id'))

    op.drop_table('visit_notifications')
    with op.batch_alter_table('visit_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_invitations_visit_id'))
        batch_op.drop_index(batch_op.f('ix_visit_invitations_token'))

    op.drop_table('visit_invitations')
    # ### end Alembic commands ###
