"""Add visitors table

Revision ID: 7c803393f498
Revises: 5f02a7302ba3
Create Date: 2026-08-01 18:34:28.516319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c803393f498'
down_revision = '5f02a7302ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('id_number', sa.String(length=100), nullable=True),
    sa.Column('passport_number', sa.String(length=100), nullable=True),
    sa.Column('vehicle_registration', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitors_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_id_number'), ['id_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_visitors_passport_number'), ['passport_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_visitors_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_vehicle_registration'), ['vehicle_registration'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitors_vehicle_registration'))
        batch_op.drop_index(batch_op.f('ix_visitors_phone'))
        batch_op.drop_index(batch_op.f('ix_visitors_passport_number'))
        batch_op.drop_index(batch_op.f('ix_visitors_id_number'))
        batch_op.drop_index(batch_op.f('ix_visitors_email'))

    op.drop_table('visitors')
    # ### end Alembic commands ###
