"""rename invitation used_at to completed_at

Revision ID: 7cb897cd594c
Revises: 793b314ca744
Create Date: 2026-08-20 08:43:35.191714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cb897cd594c'
down_revision = '793b314ca744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('used_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
