"""add QR fields to visits

Revision ID: 953963968848
Revises: 7c803393f498
Create Date: 2026-08-15 23:51:02.868033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '953963968848'
down_revision = '7c803393f498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('visitor_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('host_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('destination_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('site_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('visit_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('expected_arrival', sa.DateTime(), nullable=True),
    sa.Column('expected_departure', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('qr_token', sa.String(length=255), nullable=True),
    sa.Column('qr_generated_at', sa.DateTime(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_qr_token'), ['qr_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_visits_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_visitor_id'), ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_visits_status'))
        batch_op.drop_index(batch_op.f('ix_visits_site_id'))
        batch_op.drop_index(batch_op.f('ix_visits_qr_token'))
        batch_op.drop_index(batch_op.f('ix_visits_host_id'))
        batch_op.drop_index(batch_op.f('ix_visits_destination_id'))

    op.drop_table('visits')
    # ### end Alembic commands ###
