"""Add visit notification

Revision ID: 9cd8eb2b1fa9
Revises: 7cb897cd594c
Create Date: 2026-08-21 12:07:38.329131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cd8eb2b1fa9'
down_revision = '7cb897cd594c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_message_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_visit_notifications_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_notifications_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_notifications_recipient'), ['recipient'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_notifications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_visit_notifications_recipient'))
        batch_op.drop_index(batch_op.f('ix_visit_notifications_event'))
        batch_op.drop_index(batch_op.f('ix_visit_notifications_channel'))
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.drop_column('provider_message_id')

    # ### end Alembic commands ###
