"""Added rejected at and rejected by to visit

Revision ID: cc6309c9ce6c
Revises: db9f95e3d9f0
Create Date: 2026-08-24 22:49:54.303331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc6309c9ce6c'
down_revision = 'db9f95e3d9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_by', mysql.CHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['rejected_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('rejected_by')

    # ### end Alembic commands ###
